import { inject, Injectable, signal } from '@angular/core';

import { DUMMY_CUSTOMERS } from '../../dummy_data';
import { HttpClient } from '@angular/common/http';
import { Customer } from './customer.model';
import { tap } from 'rxjs';
import { MessageService } from '../message/message.service';

@Injectable({
  providedIn: 'root',
})
export class CustomersService {
// for Dummy data
  // get customers() {
  //   return DUMMY_CUSTOMERS;
  // };

  messageService = inject(MessageService);

  customers = signal<Customer[]>([]);
  isLoading = signal<boolean>(false);
  // errorMessage = signal<string | null>(null);
  // successMessage = signal<string | null>(null);

  private http = inject(HttpClient);
  baseUrl = 'http://localhost:8080';

  getAllCustomers() {
    this.isLoading.set(true);
    // this.errorMessage.set(null);
    return this.http.get<{customers: Customer[]}>(`${this.baseUrl}/customer`).pipe(
      tap({
        next: response => {
          this.customers.set(response.customers);
          console.log(response);
        },
        error: error => {
          console.error('Error fetching customers', error);
          this.messageService.setMessage('error',`Error fetching customers: ${error.message}`);
          // this.errorMessage.set(error.message);
        },
        complete: () => {this.isLoading.set(false)},
      })
    );
  }

  newCustomer(customerData: Partial<Customer>) { //Partial, because id will be generated by backend
    // this.errorMessage.set(null);
    this.isLoading.set(true);
    console.log(customerData);
    return this.http.post<{customerDate: Partial<Customer>}>(`${this.baseUrl}/customer`, {
      ...customerData
    }).pipe(
      tap({
        next: () => {
        console.log('Customer added successfully');
        this.messageService.setMessage('success','Customer added successfully');
        // this.successMessage.set('Customer added successfully')
        //reload customers, maybe add optimistic update
        this.getAllCustomers().subscribe();
        },
        error: error => {
            console.error('Error adding customer', error);
            this.messageService.setMessage('error',`Error adding customer: ${error.message}`);
            // this.errorMessage.set(error.message);
        },
        complete: () => {this.isLoading.set(false)},
    }))
  }

  updateCustomer(id:string, customerData: Customer) {
    // this.errorMessage.set(null);
    this.isLoading.set(true);
    console.log(customerData);
    return this.http.put<{customerData: Customer}>(`${this.baseUrl}/customer/ ${id}`, {
      ...customerData
    }).pipe(
      tap({
        next: () => {
        console.log('Customer updated successfully');
        this.messageService.setMessage('success','Customer updated successfully');
        // this.successMessage.set('Customer updated successfully')
        //reload customers, maybe add optimistic update
        this.getAllCustomers().subscribe();
        },
        error: error => {
            console.error('Error updating customer', error);
            this.messageService.setMessage('error',`Error updating customer: ${error.message}`);
            // this.errorMessage.set(error.message);
        },
        complete: () => {this.isLoading.set(false)},
    }))
  }

  deleteCustomer(id: string) {
    // this.errorMessage.set(null);
    this.isLoading.set(true);
    // this.customers.filter((customer) => customer.customerId !== id)
    return this.http.delete(`${this.baseUrl}/customer/ ${id}`).pipe(
      tap({
        next: () => {
        console.log('Customer deleted successfully');
        this.messageService.setMessage('success','Customer deleted successfully');
        // this.successMessage.set('Customer deleted successfully')
        //reload customers, maybe add optimistic updating
        this.getAllCustomers().subscribe();
        },
        error: error => {
            console.error('Error deleting customer', error);
            this.messageService.setMessage('error',`Error deleting customer: ${error.message}`);
            // this.errorMessage.set(error.message);
        },
        complete: () => {this.isLoading.set(false)},
    }))
  }


}


