import { inject, Injectable, Signal, signal } from '@angular/core';

import { DUMMY_CONTRACTS } from '../../dummy_data';
import { MessageService } from '../message/message.service';
import { Contract, StatusTransition } from './contract.model';
import { HttpClient, httpResource, HttpResourceRef } from '@angular/common/http';


@Injectable({
  providedIn: 'root',
})
export class ContractsService {
  // get contracts() {
  //   return DUMMY_CONTRACTS;
  // }

  messageService = inject(MessageService);

  contracts = signal<Contract[]>([]);
  isLoading = signal<boolean>(false);
  statusTransitions = signal<StatusTransition[]>([]);

  private http = inject(HttpClient);
  baseUrl = 'http://localhost:8080';
  
  getAllContracts() {
    this.isLoading.set(true);
    // this.errorMessage.set(null);
    this.getContracts().subscribe({
      next: response => {
          this.contracts.set(response);
          console.log(response);
        },
        error: error => {
          console.error('Error fetching contracts', error);
          this.messageService.setMessage('error',`Error fetching contracts: ${error.message}`);
          // this.errorMessage.set(error.message);
        },
        complete: () => {this.isLoading.set(false)},
    })
  }

  
  contractsByCustomerResource(customerIdSignal: Signal<string | undefined>): HttpResourceRef<{ content?: Contract[] } | undefined> {
    return httpResource(() =>
      `${this.baseUrl}/finance/contract/search?customerId=${customerIdSignal()}&pageNumber=0&pageSize=10`
    );
  }


  // getContractsByCustomerId(customerId: string) {
  //   this.isLoading.set(true);
  //   this.getContractsFilter(customerId).subscribe({
  //     next: response => {
  //       this.contracts.set(response);
  //       console.log(response);
  //     },
  //       error: error => {
  //         console.error('Error fetching contracts', error);
  //         this.messageService.setMessage('error',`Error fetching contracts: ${error.message}`);
  //         // this.errorMessage.set(error.message);
  //       },
  //       complete: () => {this.isLoading.set(false)},
  //   })
  // }

  newContract(contractData: Partial<Contract>) { //Partial, because id will be generated by backend
    // this.errorMessage.set(null);
    this.isLoading.set(true);
    console.log(contractData);
    return this.postContract(contractData).subscribe({
      next: () => {
        console.log('Contract added successfully');
        this.messageService.setMessage('success','Contract added successfully');
        // this.successMessage.set('Customer added successfully')
        //reload customers, maybe add optimistic update
        this.getAllContracts();
        },
        error: error => {
            console.error('Error adding customer', error);
            this.messageService.setMessage('error',`Error adding customer: ${error.message}`);
            // this.errorMessage.set(error.message);
            this.isLoading.set(false);
        },
        //will be set false when reload completes
        // complete: () => {this.isLoading.set(false)},
    })
  }

  editContract(id:string, contractData:Contract) {
    this.isLoading.set(true);
    console.log(contractData);
    return this.putContract(id, contractData).subscribe({
      next: () => {
        console.log('Contract updated successfully');
        this.messageService.setMessage('success','Contract updated successfully');
        //reload customers, maybe add optimistic update
        this.getAllContracts();
        },
        error: error => {
            console.error('Error updating contract', error);
            this.messageService.setMessage('error',`Error updating contract: ${error.message}`);
            this.isLoading.set(false);
        },
        //will be set false when reload completes
        // complete: () => {this.isLoading.set(false)},
    })
  }

  getAllStatusTransitions() {
    //load in background, no loading indicator !?
    return this.getStatusTransitions().subscribe({
      next: response => {
          this.statusTransitions.set(response);
          console.log(response);
        },
        error: error => {
          console.error('Error fetching status transitions', error);
          this.messageService.setMessage('error',`Error status transitions: ${error.message}`);
          // this.errorMessage.set(error.message);
        }
    })
  }

  updateContractStatus(id:string, toStatus: string) {
    this.isLoading.set(true);
    console.log(id,toStatus);
    return this.postContractStatus(id, toStatus).subscribe({
      next: () => {
        console.log('Contract status updated successfully');
        this.messageService.setMessage('success','Contract status updated successfully');
        //reload contracts, TODO change update contract in signal with response instead of reloading all
        this.getAllContracts();
        },
        error: error => {
            console.error('Error updating contract status', error);
            this.messageService.setMessage('error',`Error updating contract status: ${error.message}`);
            this.isLoading.set(false);
        },
        //will be set false when reload completes
        // complete: () => {this.isLoading.set(false)},
    })
  }


 //http calls
  getContracts() {
    return this.http.get<Contract[]>(`${this.baseUrl}/finance/contract`)
  }

  // getContractsFilter(id: string) {
  //   return this.http.get<Contract[]>(`${this.baseUrl}/finance/contract/search?customerId=${id}&pageNumber=0&pageSize=10`)
  // }

  getContractTransitions() {
    //todo get transitions and store 
  }

  postContract(contractData: Partial<Contract>) { //Partial, because id will be generated by backend
    return this.http.post<{contractData: Partial<Contract>}>(`${this.baseUrl}/finance/contract`, {
      ...contractData
    })
  }
    
  putContract(id:string, contractData: Contract) {
    return this.http.put<{contractData: Contract}>(`${this.baseUrl}/finance/contract/${id}`, {
      ...contractData
    })
  }

  postContractStatus(id:string, toStatus: string) {
    return this.http.post<{id:string, toStatus:string}>(`${this.baseUrl}/finance/contract/${id}/status`, {
      status: toStatus
    })
  }

  //not implemented on backend 
  // deleteCustomer(id: string) {
  //   return this.http.delete(`${this.baseUrl}/customer/ ${id}`)
  // }

  getStatusTransitions() {
    return this.http.get<StatusTransition[]>(`${this.baseUrl}/finance/contract/status/transition`)
  }
}
