import { computed, effect, inject, Injectable, signal } from '@angular/core';

import { MessageService } from '../message/message.service';
import { Contract, StatusTransition } from './contract.model';
import { HttpClient, httpResource } from '@angular/common/http';


@Injectable({
  providedIn: 'root',
})
export class ContractsService {

  messageService = inject(MessageService);

  contracts = signal<Contract[]>([]); //not used anymore, httpResource now used, signal created in component
  contract = signal<Contract | undefined>(undefined);
  isLoading = signal<boolean>(false);
  statusTransitions = signal<StatusTransition[]>([]);

  private http = inject(HttpClient);
  baseUrl = 'http://localhost:8080';

 
  //not used anymore
  getAllContracts() {
    this.isLoading.set(true);
    // this.errorMessage.set(null);
    this.getContracts().subscribe({
      next: response => {
          this.contracts.set(response);
          console.log(response);
        },
        error: error => {
          console.error('Error fetching contracts', error);
          this.messageService.setMessage('error',`Error fetching contracts: ${error.message}`);
          // this.errorMessage.set(error.message);
        },
        complete: () => {this.isLoading.set(false)},
    })
  }

  getContract(id:string) {
    this.isLoading.set(true);
    this.getContractById(id).subscribe({
      next: response => {
          this.contract.set(response);
          console.log(response);
        },
        error: error => {
          console.error('Error fetching contract', error);
          this.messageService.setMessage('error',`Error fetching contract: ${error.message}`);
        },
        complete: () => {this.isLoading.set(false)},
    })
  }


  newContract(contractData: Partial<Contract>) { //Partial, because id will be generated by backend
    this.isLoading.set(true);
    console.log(contractData);
    return this.postContract(contractData).subscribe({
      next: () => {
        console.log('Contract added successfully');
        this.messageService.setMessage('success','Contract added successfully');
        this.contractsResource.reload();
      },
      error: error => {
          console.error('Error adding customer', error);
          this.messageService.setMessage('error',`Error adding customer: ${error.message}`);
          this.isLoading.set(false);
      },
    })
  }

  editContract(id:string, contractData:Contract) {
    this.isLoading.set(true);
    console.log(contractData);
    return this.putContract(id, contractData).subscribe({
      next: () => {
        console.log('Contract updated successfully');
        this.messageService.setMessage('success','Contract updated successfully');
        this.contractsResource.reload();
        },
        error: error => {
            console.error('Error updating contract', error);
            this.messageService.setMessage('error',`Error updating contract: ${error.message}`);
            this.isLoading.set(false);
        },
    })
  }

  getAllStatusTransitions() {
    //load in background, no loading indicator !?
    return this.getStatusTransitions().subscribe({
      next: response => {
          this.statusTransitions.set(response);
          console.log(response);
        },
        error: error => {
          console.error('Error fetching status transitions', error);
          this.messageService.setMessage('error',`Error status transitions: ${error.message}`);
        }
    })
  }

  updateContractStatus(id:string, toStatus: string) {
    this.isLoading.set(true);
    console.log(id,toStatus);
    return this.postContractStatus(id, toStatus).subscribe({
      next: () => {
        console.log('Contract status updated successfully');
        this.messageService.setMessage('success','Contract status updated successfully');
        //reload contract
        this.getContract(id);
        },
        error: error => {
            console.error('Error updating contract status', error);
            this.messageService.setMessage('error',`Error updating contract status: ${error.message}`);
            this.isLoading.set(false);
        },
    })
  }


 //http calls

 //not used anymore, now using httpResource and search contracts API
  getContracts() {
    return this.http.get<Contract[]>(`${this.baseUrl}/finance/contract`)
  }

  getContractById(id: string) {
    return this.http.get<Contract>(`${this.baseUrl}/finance/contract/${id}`)
  }

  getContractTransitions() {
    //todo get transitions and store 
  }

  postContract(contractData: Partial<Contract>) { //Partial, because id will be generated by backend
    return this.http.post<{contractData: Partial<Contract>}>(`${this.baseUrl}/finance/contract`, {
      ...contractData
    })
  }
    
  putContract(id:string, contractData: Contract) {
    return this.http.put<{contractData: Contract}>(`${this.baseUrl}/finance/contract/${id}`, {
      ...contractData
    })
  }

  postContractStatus(id:string, toStatus: string) {
    return this.http.post<{id:string, toStatus:string}>(`${this.baseUrl}/finance/contract/${id}/status`, {
      status: toStatus
    })
  }

  //not implemented on backend ??
  // deleteCustomer(id: string) {
  //   return this.http.delete(`${this.baseUrl}/customer/ ${id}`)
  // }

  getStatusTransitions() {
    return this.http.get<StatusTransition[]>(`${this.baseUrl}/finance/contract/status/transition`)
  }

  ///httpResource automatically updates on input signal changes; exposes signals for Loading and error(todo)
  //input signals are updated via effect in overview component
  customerIdService = signal<string | undefined>(undefined);
  contractsResource = httpResource(() =>
      `${this.baseUrl}/finance/contract/search?customerId=${this.customerIdService()}&pageNumber=0&pageSize=10`
  );
  contractsList = computed(() => {
    const resource = this.contractsResource.value() as { content?: Contract[] } | undefined;
    return resource && Array.isArray(resource.content) ? resource.content : [];
  });
  resourceIsLoading = computed(() => this.contractsResource.isLoading());
  resourceError = computed(() => this.contractsResource.error());

  private errorEffect = effect(() => {
    const error = this.contractsResource.error();
    console.log('Error effect triggered:', error);
    if (error !== undefined && error.message)
      this.messageService.setMessage('error', `Error fetching contracts: ${error?.message ?? ''}`);
  });
  

}
