export const DUMMY_CUSTOMERS = [
    {
      id: 'u1',
      name: 'John Doe',
      tax_identification_number: '2',
      tax_identification_type: '???',
      tax_regime: '??',
      annual_revenue: 2000,
      currency: 'EUR',
      country: 'Germany',
      address: 'Dort 44',
      postal_code: '66677',
      business_sector: 'Content Creator',
      establishment_date: '1970-01-01',
      notes: 'John Doe is a very special client ... very, very special',
    },
    {
      id: 'u2',
      name: 'Emily Thompson',
      tax_identification_number: '',
      tax_identification_type: '',
      tax_regime: '',
      annual_revenue: 0,
      currency: '',
      country: '',
      address: '',
      postal_code: '',
      business_sector: '',
      establishment_date: '',
      notes: '',
    },
    {
      id: 'u3',
      name: 'Marcus Johnson',
      tax_identification_number: '',
      tax_identification_type: '',
      tax_regime: '',
      annual_revenue: 0,
      currency: '',
      country: '',
      address: '',
      postal_code: '',
      business_sector: '',
      establishment_date: '',
      notes: '',
    },
    {
      id: 'u4',
      name: 'David Miller',
      tax_identification_number: '',
      tax_identification_type: '',
      tax_regime: '',
      annual_revenue: 0,
      currency: '',
      country: '',
      address: '',
      postal_code: '',
      business_sector: '',
      establishment_date: '',
      notes: '',
    },
    {
      id: 'u5',
      name: 'Priya Patel',
      tax_identification_number: '',
      tax_identification_type: '',
      tax_regime: '',
      annual_revenue: 0,
      currency: '',
      country: '',
      address: '',
      postal_code: '',
      business_sector: '',
      establishment_date: '',
      notes: '',
    },
    {
      id: 'u6',
      name: 'Arjun Singh',
      tax_identification_number: '',
      tax_identification_type: '',
      tax_regime: '',
      annual_revenue: 0,
      currency: '',
      country: '',
      address: '',
      postal_code: '',
      business_sector: '',
      establishment_date: '',
      notes: '',
    },
  ];
  

  export const DUMMY_CONTRACTS = [
    {
      contract_id: 'c1',
      customer_id: 'u1',
      total_amount: 20000,
      contract_type: 'consulting',
      frequency: 'monthly',
      payment_day: 1,
      start_date: '2024-01-01',
      end_date: '2024-12-12',
      status: 'active',
      termination_clause: 'blabla',
      penalty_fee: 15.99,
    },
    {
      contract_id: 'c2',
      customer_id: 'u2',
      total_amount: 10000,
      contract_type: 'consulting',
      frequency: 'at once',
      payment_day: 1,
      start_date: '2024-01-01',
      end_date: '2024-12-12',
      status: 'active',
      termination_clause: 'blabla',
      penalty_fee: 19.99,
    }
  ]